version: 0.2
phases:
  pre-build:
    commands:
      - echo "we are on pre-build stage."
  build:
    commands:
      - echo "we are on build stage."
      - mvn clean install
  post-build:
    commands:
      - echo "we are on post-build stage."
artifacts:
  files:
    - target/**/*